"""Alert evaluation package — rules produce candidates; CLI delivers separately.

Compatibility facade: public symbols remain importable as ``spx_spark.alert_engine``.
"""

from __future__ import annotations

from spx_spark.alert_engine.cli import main, parse_args, print_alerts, run
from spx_spark.alert_engine.constants import (
    ATM_IV_CHANGE_1H_THRESHOLD,
    ATM_IV_JUMP_THRESHOLD,
    BAD_QUALITIES,
    BAD_SURFACE_QUALITIES,
    BASELINE_INSTRUMENTS,
    BLOCKING_SURFACE_QUALITIES,
    DEGRADED_SURFACE_QUALITIES,
    EM_MOVE_FRACTIONS,
    IBKR_INTERRUPTED_SESSION_STATUSES,
    IBKR_TRANSITIONAL_SESSION_STATUSES,
    MOVE_HIGH_SEVERITY_EM_FRACTION_DEFAULT,
    MOVE_THRESHOLDS_BPS,
    OPTION_GAMMA_ALERT_STATES,
    QUIET_EM_THRESHOLD_FLOOR_BPS_DEFAULT,
    SKEW_25D_STEEPENING_THRESHOLD,
    SKEW_STEEPENING_THRESHOLD,
    SURFACE_SHIFT_1H_THRESHOLD,
    SURFACE_SHIFT_THRESHOLD,
    TERM_GAP_THRESHOLD,
    WALL_DEDUP_BAND_POINTS,
)
from spx_spark.alert_engine.evaluator import (
    evaluate_alerts,
    evaluate_payload,
    load_current_iv_surface,
)
from spx_spark.alert_engine.rules_data import find_best, quote_health_alert
from spx_spark.alert_engine.rules_options import (
    gamma_regime_observation_stable,
    gamma_regime_state_path,
    iv_surface_alerts,
    iv_surface_freshness_alert,
    iv_surface_movement_detail,
    iv_surface_movement_severity,
    load_gamma_regime_state,
    magnitude_bucket,
    option_coverage_is_fresh,
    option_freshness_alert,
    option_map_alerts,
    persist_gamma_regime_observations,
    wall_dedup_band,
)
from spx_spark.alert_engine.rules_price import (
    build_movement_state_payload,
    effective_move_threshold_bps,
    front_expected_move_pct,
    load_movement_state,
    move_from_close_bps,
    movement_alerts,
    movement_bucket_and_direction,
    movement_state_path,
    movement_threshold_for_window,
    parse_movement_instrument_state,
    persist_movement_state_snapshot,
    save_movement_state,
)
from spx_spark.alert_engine.rules_system import (
    build_system_event_state_payload,
    hyperliquid_proxy_gate,
    hyperliquid_proxy_usable,
    ibkr_feed_unavailable_for_fallback,
    ibkr_gateway_login_alert,
    ibkr_session_event_alert,
    ibkr_session_is_position_critical,
    ibkr_session_status,
    load_provider_failover_state,
    load_system_event_state,
    market_context_alerts,
    persist_system_event_state,
    provider_failover_event_alert,
    provider_state_for,
    provider_state_is_recent,
    proxy_fallback_watch_alerts,
    save_system_event_state,
    system_event_alerts,
    system_event_state_path,
)
from spx_spark.notifier import notify_payload
from spx_spark.position_alerts import reconcile_position_event_acknowledgements
from spx_spark.storage import LatestStateStore

__all__ = [
    "ATM_IV_CHANGE_1H_THRESHOLD",
    "ATM_IV_JUMP_THRESHOLD",
    "BAD_QUALITIES",
    "BAD_SURFACE_QUALITIES",
    "BASELINE_INSTRUMENTS",
    "BLOCKING_SURFACE_QUALITIES",
    "DEGRADED_SURFACE_QUALITIES",
    "EM_MOVE_FRACTIONS",
    "IBKR_INTERRUPTED_SESSION_STATUSES",
    "IBKR_TRANSITIONAL_SESSION_STATUSES",
    "MOVE_HIGH_SEVERITY_EM_FRACTION_DEFAULT",
    "MOVE_THRESHOLDS_BPS",
    "OPTION_GAMMA_ALERT_STATES",
    "QUIET_EM_THRESHOLD_FLOOR_BPS_DEFAULT",
    "SKEW_25D_STEEPENING_THRESHOLD",
    "SKEW_STEEPENING_THRESHOLD",
    "SURFACE_SHIFT_1H_THRESHOLD",
    "SURFACE_SHIFT_THRESHOLD",
    "TERM_GAP_THRESHOLD",
    "WALL_DEDUP_BAND_POINTS",
    "build_movement_state_payload",
    "build_system_event_state_payload",
    "effective_move_threshold_bps",
    "evaluate_alerts",
    "evaluate_payload",
    "find_best",
    "front_expected_move_pct",
    "gamma_regime_observation_stable",
    "gamma_regime_state_path",
    "hyperliquid_proxy_gate",
    "hyperliquid_proxy_usable",
    "ibkr_feed_unavailable_for_fallback",
    "ibkr_gateway_login_alert",
    "ibkr_session_event_alert",
    "ibkr_session_is_position_critical",
    "ibkr_session_status",
    "iv_surface_alerts",
    "iv_surface_freshness_alert",
    "iv_surface_movement_detail",
    "iv_surface_movement_severity",
    "load_current_iv_surface",
    "load_gamma_regime_state",
    "load_movement_state",
    "load_provider_failover_state",
    "LatestStateStore",
    "load_system_event_state",
    "magnitude_bucket",
    "main",
    "market_context_alerts",
    "move_from_close_bps",
    "movement_alerts",
    "movement_bucket_and_direction",
    "movement_state_path",
    "movement_threshold_for_window",
    "notify_payload",
    "option_coverage_is_fresh",
    "option_freshness_alert",
    "option_map_alerts",
    "parse_args",
    "parse_movement_instrument_state",
    "persist_gamma_regime_observations",
    "persist_movement_state_snapshot",
    "persist_system_event_state",
    "print_alerts",
    "provider_failover_event_alert",
    "provider_state_for",
    "provider_state_is_recent",
    "proxy_fallback_watch_alerts",
    "quote_health_alert",
    "reconcile_position_event_acknowledgements",
    "run",
    "save_movement_state",
    "save_system_event_state",
    "system_event_alerts",
    "system_event_state_path",
    "wall_dedup_band",
]

if __name__ == "__main__":
    main()
